# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
include: ["_pages"]
auto: false
pygments: false

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Jonathon Bolster
tagline: Programming, life, random
author :
  name : Jonathon Bolster
  email : jonathon@bolsterweb.com
  github : jbolster
  twitter : jbolster
  facebook: bolster
  gplus: 115124500511465538690
  stackexchange : 4b41b43950c54ca1b724248392596be9

url : http://www.bolsterweb.com

disqus:
  shortname: jonathonbolster
